from pathlib import Path

import pandas as pd
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas

from config import Config


class ExportService:
    def __init__(self):
        Path(Config.REPORT_FOLDER).mkdir(parents=True, exist_ok=True)

    def export_excel(self, frame, name="skinseasonai_export.xlsx"):
        path = Path(Config.REPORT_FOLDER) / name
        with pd.ExcelWriter(path, engine="openpyxl") as writer:
            frame.to_excel(writer, index=False, sheet_name="records")
            frame.groupby(["season", "disease"], dropna=False)["incidence"].sum().reset_index().to_excel(
                writer, index=False, sheet_name="season_disease"
            )
        return path

    def export_pdf(self, summary, name="skinseasonai_report.pdf"):
        path = Path(Config.REPORT_FOLDER) / name
        pdf = canvas.Canvas(str(path), pagesize=A4)
        width, height = A4
        y = height - 60
        pdf.setFont("Helvetica-Bold", 16)
        pdf.drawString(50, y, "SkinSeasonAI Analysis Report")
        y -= 40
        pdf.setFont("Helvetica", 11)
        for key, value in summary.items():
            if key == "numeric_summary":
                continue
            pdf.drawString(50, y, f"{key}: {value}")
            y -= 22
        pdf.drawString(50, y - 20, "Generated by SkinSeasonAI Flask system.")
        pdf.save()
        return path

